### ISSUE TITLE
I am not able to see model with dynamic background using my phone's camera. Only able to see is 3D model.

### ISSUE THREAD

**Issue by bhargavbhatiya** [echoARxyz/Flutter-Unity-ARFoundation-echoAR-example#1]

**Comment by alon-grinshpoon** [comment]
It seems like you built the wrong scene in Unity - make sure to open & build the scene under _Assets/ARFundtion/Scenes/SimpleAR/SimpleAR.unity_ and not the scene under _Assets/echoAR/Example/sample.unity_. This can be set in the Unity _Build Settings_.

Also, make sure your API key is set in the echoAR _game object_ and _prefab_ when using  _Assets/ARFundtion/Scenes/SimpleAR/SimpleAR.unity_.
